---
- name: Configure Ansible Controller
  hosts: ansible-lab-controller
  tasks:
  - name: Ensure latest Ansible version
    become: yes
    ansible.builtin.package:
      name:
      - ansible
      - git
      state: latest

- name: Universal host configuration
  hosts: ansible_lab_hosts
  vars:
    ansible_become: true
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90

- name: Configure DNS Server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  tasks:
  - name: Install dnsmasq
    ansible.bulitin.package:
      name: dnsmasq
      state: latest
    notify: Restrart dnsmasq
  - name: Set local hostname
    ansible.bulitin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.4'
      line: '10.1.2.4 localhost {{ ansible_hostname }}'
    notify: Restrart dnsmasq
  - name: Disable exsisting DNS
    ansible.bulitin.sevice:
      name: system-resolved
      state: stopped
  - name: Set dnsmasq configuration file
    ansible.builtin.copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
    notify: Restrart dnsmasq
  handlers:
  - name: Start dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted
    