---
- name: Configure Ansible Controller
  hosts: ansible-lab-controller
  tasks:
  - name: Ensure latest Ansible version
    ansible.builtin.package:
      become: yes
      name:
      - ansible
      - git
      state: latest