---

- name: Configure Samba
  hosts: ansible-lab-host3
  vars:
    ansible_become: True
  tasks:
  - name: Install client deps
    package:
      name: cifs-utils
      state: latest
  - name: Add share Mount
    mount:
      src: //10.1.2.5/testshare
      path: /mnt/smbshare
      fstype: cifs
      state: mounted
  - name: Set mount as writeable
    file:
      path: /mnt/smbshare
      state: directory
      mode: '0777'

- name: Configure Samba Server
  hosts: ansible-lab-host2
  vars:
    ansible_become: true
  roles:
  - ansible-role-samba






