---
admin_un: '{{ vault_admin_un }}'
admin_pw: '{{ vault_admin_pw }}'

samba_server_string: 'Ansible Lab File Server'
samba_workgroup: TESTGROUP
samba_users:
- name: '{{ admin_un }}'
  password: '{{ admin_pw }}'
samba_shares_root: /srv/samba
samba_shares:
- name: testshare
  comment: 'Only accessible to {{ admin_un }}'
  valid_users: '{{ admin_un}}'
  write_list: '{{ admin_un }}'
  group: '{{ admin_un }}'
  browseable: 'yes'
